#!/usr/bin/env bash

# FROM
docker build -t reimii/from from

docker ls

# RUN
docker build -t reimii/run run
docker build -t reimii/run run --no-cache

# CMD 
docker build -t reimii/command command
docker container create --name command reimii/command
docker container start command
docker container logs command

# LABEL
docker build -t reimii/label label
docker image inspect reimii/label

