#!/usr/bin/env bash

# FROM
docker build -t reimii/from from

docker ls

# RUN
docker build -t reimii/run run
docker build -t reimii/run run --no-cache

# CMD 
docker build -t reimii/command command
docker container create --name command reimii/command
docker container start command
docker container logs command

# LABEL
docker build -t reimii/label label
docker image inspect reimii/label

# ADD
docker build -t reimii/add add
docker container create --name add reimii/add
docker container start add
docker container logs add

# COPY 
docker build -t reimii/copy copy
docker container create --name copy reimii/copy
docker container start copy
docker container logs copy

# INGNORE 
docker build -t reimii/ignore ignore
docker container create --name ignore reimii/ignore
docker container start ignore
docker container logs ignore

# EXPOSE 
docker build -t reimii/expose expose
docker image inspect reimii/expose
docker container create --name expose -p 80:8080 reimii/expose
docker container start expose
docker container stop expose
